### ISSUE TITLE
3 elements placed horizontally

### ISSUE THREAD

**Issue by thehugor8** [Plathena/landing-page#6]
replace the original text and icons by the mentioned below:

1. **Automate your Data journey** 
Still working manually? Data collection was never made so simple. 

2. **Make smarter decisions and step ahead of your competitors**
Now you can transform loads of raw data into meaningful and structured information. 

3. **Reduce your costs and save time**
Working as efficiently as innovation allows is key for business grow

(the text is located below each illustration)

**Comment by norwindijkman** [comment]
The plan is now to copy-paste other websites into our own website to save time

**Comment by norwindijkman** [comment]
We could use these: https://gatsby-starter-business.netlify.com/

And replace them with our own images and text of course

**Comment by norwindijkman** [comment]
All of this is available too: http://demo.themefisher.com/demos/?theme=blue
